namespace PjskBundle2Parts.Models;

public sealed record ExporterConfig(
    string? Output,
    string? Motion,
    string? Master,
    string? AssetRoot,
    bool? EmitCostumeRegistries,
    bool? EmitRuntimeRoleCatalog,
    bool? EmitPartPackages,
    bool? EmitRoleRuntimes,
    bool? ExportFaceMotion,
    int? PartCostume3dId,
    string? PartType,
    string? PartUnit,
    int[]? RoleCharacter3dIds,
    string? SourcePath,
    string? Manifest,
    int? PartPackageProcessConcurrency,
    int? PartPackageWorkers,
    int? PartPackageCoreCount,
    int? PartPackageShardCount,
    int? PartPackageShardIndex,
    string? PartPackageClaimDirectory,
    string? AssetStudioLogLevel,
    bool? CompactTextures,
    bool? OptimizeTextureStore,
    string? SharedContentStore,
    string? CompiledContentStore,
    string? PngOptimize,
    string? TextureFormat,
    int? TextureCompactWorkers,
    string? AssetStudioRoot,
    bool? ConvertModelTextures,
    string? PartPackageWorkList,
    string? BundleHashIndex
);
